import { describe,expect,it,vi } from 'vitest'
import { needsPrivateDataApproval } from './workspaceSecurity'
import { callTool } from './tools'
import { fenceQaContext } from './accountFence'
describe('private workspace data boundaries',()=>{
  it('fences delayed artifact reads and prevents subsequent writes in the next account',async()=>{let active=true;let finish!:(value:Buffer)=>void;const save=vi.fn();const context={runs:{saveDraft:save},designs:{readNormalized:()=>new Promise<Buffer>(resolve=>{finish=resolve})}} as any;const fenced=fenceQaContext(context,()=>{if(!active)throw new Error('Account changed')});const pending=fenced.designs.readNormalized('owned-page','desktop');active=false;finish(Buffer.from('private image'));await expect(pending).rejects.toThrow('Account changed');expect(()=>fenced.runs.saveDraft('old-run','desktop',[])).toThrow('Account changed');expect(save).not.toHaveBeenCalled()})
  it('requires review before catalog data becomes network input',()=>{expect(needsPrivateDataApproval('http_request',{method:'GET',url:'https://site.test/?secret=data'},'https://site.test/')).toBe(true);expect(needsPrivateDataApproval('browser_type',{text:'private record'})).toBe(true);expect(needsPrivateDataApproval('browser_open',{url:'/new?q=private'},'https://site.test/')).toBe(true);expect(needsPrivateDataApproval('browser_open',{url:'https://site.test/'},'https://site.test/')).toBe(false);expect(needsPrivateDataApproval('workspace_detail',{})).toBe(false)})
  it('rejects stale account access before executing tool code',async()=>{const ctx={assertAccess:()=>{throw new Error('The account changed')}} as any;const r=await callTool('parity_help',{topic:'overview'},ctx);expect(r.isError).toBe(true);expect(r.text).toContain('account changed')})
  it('does not expose arbitrary-file tools or allow a model to approve a proposal',async()=>{const ctx={agentAccess:true,allowedTools:new Set(['workspace_search'])} as any;expect((await callTool('parity_help',{},ctx)).isError).toBe(true);expect((await callTool('workspace_apply',{id:'guessed'},ctx)).isError).toBe(true);expect((await callTool('set_design',{path:'C:/secret.png'},ctx)).isError).toBe(true)})
})
