import { useEffect, useMemo, useState } from 'react'
import type { AuditFinding, FindingReview, OrganizerSnapshot, FindingUpdate } from '../../../../shared/qaOrganizer'
import { PictureLightbox, shortLink, type FindingPicture } from '../QaFindings'
import RichText from './RichText'
import { REVIEW_LABELS } from './findingSheet'
import './Organizer.css'
function FindingItem({item,snapshot,selected,toggle,update}:{item:AuditFinding;snapshot:OrganizerSnapshot;selected:boolean;toggle:()=>void;update:(changes:FindingUpdate[],revision?:number)=>Promise<boolean>}){
  const [draft,setDraft]=useState(item.cells);const [baseRevision,setBaseRevision]=useState(snapshot.revision);const [dirty,setDirty]=useState(false);const [picture,setPicture]=useState<FindingPicture|null>(null);const [zoom,setZoom]=useState<FindingPicture|null>(null);const [loading,setLoading]=useState(false);const [pictureIndex,setPictureIndex]=useState(0)
  useEffect(()=>{if(!dirty)setDraft(item.cells)},[item.cells,dirty])
  const change=(column:string,value:string)=>{if(!dirty)setBaseRevision(snapshot.revision);setDraft(previous=>({...previous,[column]:value}));setDirty(true)}
  const priority=snapshot.columns.find(column=>/priority|severity|impact/i.test(column));const status=snapshot.columns.find(column=>/^status$/i.test(column));const remark=snapshot.columns.find(column=>/^(remarks|issue|description|finding|comment)s?$/i.test(column))||'Remarks'
  const load=(index=pictureIndex)=>{if((picture&&index===pictureIndex)||!item.evidence||loading)return;setPictureIndex(index);setLoading(true);void window.electronAPI.qaFindingsPicture(snapshot.projectKey,item.id,index).then(setPicture).catch(()=>setPicture(null)).finally(()=>setLoading(false))}
  return <article className={`qa-organizer-item ${item.review}`}><div className="qa-organizer-item-top"><input type="checkbox" aria-label={`Select finding ${item.cells.Section||item.id}`} checked={selected} onChange={toggle}/><span className="qa-organizer-state">{REVIEW_LABELS[item.review]}</span><small>{[...new Set(item.sources.map(s=>s.breakpoint))].join(' · ')}</small></div>
    <details onToggle={event=>{if(event.currentTarget.open)load()}}><summary><strong>{item.cells.Section||'Finding'}</strong><div className="qa-organizer-remark"><RichText text={item.cells[remark]||''}/></div></summary><div className="qa-organizer-edit"><label>Section<input value={draft.Section||''} onChange={e=>change('Section',e.target.value)}/></label><label>{remark}<textarea rows={3} value={draft[remark]||''} onChange={e=>change(remark,e.target.value)}/></label>
      {[priority,status].filter((column):column is string=>!!column).map(column=><label key={column}>{column}{snapshot.choices?.[column]?<select value={draft[column]||''} onChange={e=>change(column,e.target.value)}><option value="">Not set</option>{snapshot.choices[column].map(value=><option key={value}>{value}</option>)}</select>:<input value={draft[column]||''} onChange={e=>change(column,e.target.value)}/>}</label>)}
      {dirty&&<div className="qa-organizer-actions"><button onClick={()=>{const changes=Object.fromEntries(Object.entries(draft).filter(([key,value])=>item.cells[key]!==value));void update([{id:item.id,cells:changes}],baseRevision).then(ok=>{if(ok)setDirty(false)})}}>Save changes</button><button onClick={()=>{setDraft(item.cells);setDirty(false)}}>Cancel</button></div>}
      {loading?<span role="status">Loading evidence…</span>:picture?<button className="qa-organizer-picture" onClick={()=>setZoom(picture)} aria-label="Enlarge finding evidence"><img src={picture.src} alt={picture.caption||'Annotated evidence'}/></button>:<small>{item.evidence?'Evidence is unavailable.':'No screenshot needed for this finding.'}</small>}
      <div className="qa-organizer-actions">{(item.evidenceSet||[]).map((_image,index)=><button key={index} aria-pressed={pictureIndex===index} onClick={()=>load(index)}>Evidence {index+1}</button>)}</div><small className="qa-organizer-provenance">Audit {item.sources.map(s=>s.runId).filter((v,i,a)=>a.indexOf(v)===i).join(', ')}</small></div></details>
    <div className="qa-organizer-actions">{(['accepted','dismissed','draft'] as FindingReview[]).filter(state=>state!==item.review).map(review=><button key={review} onClick={()=>void update([{id:item.id,review}])}>{review==='accepted'?'Accept':review==='dismissed'?'Dismiss':'Restore to draft'}</button>)}</div><PictureLightbox picture={zoom} onClose={()=>setZoom(null)}/>
  </article>
}
export default function AuditOrganizer({snapshot,loading,error,saving,refresh,update}: {snapshot:OrganizerSnapshot|null;loading:boolean;error:string;saving:boolean;refresh:()=>Promise<void>;update:(changes:FindingUpdate[],revision?:number)=>Promise<boolean>}){
  const [query,setQuery]=useState('');const [page,setPage]=useState('');const [run,setRun]=useState('');const [bp,setBp]=useState('');const [kind,setKind]=useState('');const [review,setReview]=useState('');const [selected,setSelected]=useState<Set<string>>(new Set());const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false)
  const items=snapshot?.findings.filter(f=>!f.mergedInto)||[]
  useEffect(()=>{setSelected(new Set());setPage('');setRun('');setBp('');setReview('');setNotice('')},[snapshot?.projectKey])
  const visible=useMemo(()=>items.filter(item=>(!page||item.pageUrl===page)&&(!run||item.sources.some(s=>s.runId===run))&&(!bp||item.sources.some(s=>s.breakpoint===bp))&&(!review||item.review===review)&&(!kind||(kind==='suggestion')===/ENHANCEMENT|Suggestion:/i.test(Object.values(item.cells).join(' ')))&&(!query||Object.values(item.cells).join(' ').toLowerCase().includes(query.toLowerCase()))),[items,page,run,bp,review,kind,query])
  const ids=visible.filter(item=>selected.has(item.id)).map(item=>item.id)
  const action=async(work:()=>Promise<{success:boolean;error?:string;count?:number}>)=>{setBusy(true);setNotice('');try{const result=await work();setNotice(result.success?result.count?`Copied ${result.count} row${result.count===1?'':'s'}.`:'Done.':result.error||'Could not complete this action.');await refresh()}catch(cause){setNotice((cause as Error).message)}finally{setBusy(false)}}
  if(loading)return <div className="qa-organizer-loading" role="status" aria-label="Loading findings"><i/><i/><i/></div>
  if(!snapshot)return <div className="qa-organizer-empty"><p>{error||'Open a project to organize its audit findings.'}</p><button onClick={()=>void refresh()}>Retry</button></div>
  return <div className="qa-organizer"><header><strong>{snapshot.projectName}</strong><button onClick={()=>window.dispatchEvent(new CustomEvent('parity:open-ai-tracker',{detail:{projectKey:snapshot.projectKey}}))}>Open in tracker <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18"/></svg></button></header>
    <input type="search" aria-label="Search findings" placeholder="Search findings…" value={query} onChange={e=>setQuery(e.target.value)}/>
    <div className="qa-organizer-filters"><select aria-label="Filter findings by page" value={page} onChange={e=>setPage(e.target.value)}><option value="">All pages</option>{[...new Set(items.map(item=>item.pageUrl))].map(value=><option key={value} value={value}>{shortLink(value)}</option>)}</select><select aria-label="Filter findings by audit" value={run} onChange={e=>setRun(e.target.value)}><option value="">All audits</option>{[...new Set(items.flatMap(item=>item.sources.map(s=>s.runId)))].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter findings by breakpoint" value={bp} onChange={e=>setBp(e.target.value)}><option value="">All breakpoints</option>{['desktop','tablet','mobile'].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter findings by type" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option><option value="defect">Defects</option><option value="suggestion">Suggestions</option></select><select aria-label="Filter findings by review" value={review} onChange={e=>setReview(e.target.value)}><option value="">All review states</option>{Object.entries(REVIEW_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
    {(error||notice)&&<p className="qa-organizer-error" role="status">{error||notice} {error&&<button onClick={()=>void refresh()}>Refresh</button>}</p>}
    <div className="qa-organizer-selection"><label><input type="checkbox" aria-label="Select all visible findings" checked={!!visible.length&&ids.length===visible.length} onChange={e=>setSelected(e.target.checked?new Set(visible.map(item=>item.id)):new Set())}/> {ids.length?`${ids.length} selected`:`${visible.length} finding${visible.length===1?'':'s'}`}</label><small>{saving?'Saving…':'Saved locally'}</small></div>
    {ids.length>0&&<div className="qa-organizer-actions bulk">{(['accepted','dismissed','draft'] as FindingReview[]).map(state=><button key={state} disabled={busy||saving} onClick={()=>void update(ids.map(id=>({id,review:state})))}>{state==='accepted'?'Accept':state==='dismissed'?'Dismiss':'Restore'}</button>)}<button disabled={busy} onClick={()=>void action(()=>window.electronAPI.qaFindingsCopy(snapshot.projectKey,ids))}>Copy rows</button><button disabled={busy} onClick={()=>void action(()=>window.electronAPI.qaFindingsShare(snapshot.projectKey,ids))}>Share evidence</button></div>}
    <div className="qa-organizer-list">{!visible.length?<div className="qa-organizer-empty"><p>{items.length?'No findings match these filters.':'Your audit findings will appear here as the agent saves them.'}</p></div>:[...new Set(visible.map(item=>item.pageUrl))].map(url=><section key={url}><h4 title={url}>{shortLink(url)}<small>{visible.filter(item=>item.pageUrl===url).length} items</small></h4>{visible.filter(item=>item.pageUrl===url).sort((a,b)=>b.createdAt-a.createdAt).map(item=><FindingItem key={item.id} item={item} snapshot={snapshot} selected={selected.has(item.id)} toggle={()=>setSelected(previous=>{const next=new Set(previous);if(next.has(item.id))next.delete(item.id);else next.add(item.id);return next})} update={update}/>)}</section>)}</div>
    <footer><button disabled={busy} onClick={()=>void action(()=>window.electronAPI.qaFindingsImport(snapshot.projectKey))}>Import past findings</button><button disabled={busy} onClick={()=>void refresh()}>Refresh</button></footer>
  </div>
}
