import { useEffect, useMemo, useRef, useState } from 'react'
import { Workbook } from '@fortune-sheet/react'
import type { Sheet } from '@fortune-sheet/core'
import '@fortune-sheet/react/dist/index.css'
import type { FindingUpdate, OrganizerSnapshot } from '../../../../shared/qaOrganizer'
import { AI_SHEET_ID, findingSheet, findingSheetChanges } from './findingSheet'
import './Organizer.css'
export default function ManagedQaWorkbook({snapshot,update,manualSheets,onManualChange}:{snapshot:OrganizerSnapshot;update:(changes:FindingUpdate[],revision?:number)=>Promise<boolean>;manualSheets:Sheet[];onManualChange:(data:Sheet[])=>void}){
  const [sort,setSort]=useState('newest');const [error,setError]=useState('');const [pending,setPending]=useState<FindingUpdate[]>([]);const [saving,setSaving]=useState(false);const [reset,setReset]=useState(0);const [theme,setTheme]=useState(0);const active=useRef(AI_SHEET_ID);const [activeSheet,setActiveSheet]=useState(AI_SHEET_ID)
  const baseline=useRef(snapshot); if(!pending.length)baseline.current=snapshot
  const shown=baseline.current
  const colors=()=>{const css=getComputedStyle(document.documentElement);return{bg:css.getPropertyValue('--bg-card').trim(),text:css.getPropertyValue('--text-primary').trim(),border:css.getPropertyValue('--border-color').trim()}}
  const rowHeader=(text:string,_index:number,top:number,width:number,height:number,ctx:CanvasRenderingContext2D)=>{const color=colors();ctx.save();ctx.fillStyle=color.bg;ctx.fillRect(0,top,width,height);ctx.strokeStyle=color.border;ctx.strokeRect(0,top,width,height);ctx.fillStyle=color.text;ctx.font='11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,width/2,top+height/2);ctx.restore();return false}
  const columnHeader=(text:string,_index:number,left:number,width:number,height:number,ctx:CanvasRenderingContext2D)=>{const color=colors();ctx.save();ctx.fillStyle=color.bg;ctx.fillRect(left,0,width,height);ctx.strokeStyle=color.border;ctx.strokeRect(left,0,width,height);ctx.fillStyle=color.text;ctx.font='11px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,left+width/2,height/2);ctx.restore();return false}
  useEffect(()=>{const signature=()=>{const css=getComputedStyle(document.documentElement);return ['--bg-card','--text-primary','--accent-color'].map(key=>css.getPropertyValue(key)).join('|')};let current=signature();const observer=new MutationObserver(()=>{const next=signature();if(next!==current){current=next;setTheme(v=>v+1)}});observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme','style','class']});return()=>observer.disconnect()},[])
  const sheet=useMemo(()=>{const css=getComputedStyle(document.documentElement);const projection={...shown,findings:shown.findings.map(item=>{const edit=pending.find(change=>change.id===item.id);return edit?{...item,cells:{...item.cells,...edit.cells},review:edit.review||item.review}:item})};return findingSheet(projection,{bg:css.getPropertyValue('--bg-card').trim()||'#fff',text:css.getPropertyValue('--text-primary').trim()||'#222',accent:css.getPropertyValue('--accent-color').trim()||'#666'},sort)},[shown,sort,theme])
  // FortuneSheet owns live editing state. Replacing its data on each callback clears active inputs.
  const data=useMemo(()=>[{...sheet,status:active.current===AI_SHEET_ID?1:0},...manualSheets.filter(s=>s.id!==AI_SHEET_ID).map((s,index)=>({...s,id:s.id||`manual-${index}`,order:index+1,status:(s.id||`manual-${index}`)===active.current?1:0}))],[snapshot.projectKey,sort,reset,theme])
  const seenRevision=useRef(snapshot.revision)
  useEffect(()=>{
    const input=document.querySelector('.qa-tracker-dialog .luckysheet-input-box')||document.querySelector('.qa-managed-workbook .luckysheet-input-box')
    if(snapshot.revision!==seenRevision.current&&!pending.length&&!saving&&(!input||Number((input as HTMLElement).style.zIndex)<0)){seenRevision.current=snapshot.revision;setReset(value=>value+1)}
  },[snapshot.revision,pending.length,saving])
  return <div className="qa-managed-workbook" style={{colorScheme:parseInt(colors().bg.replace('#','').slice(0,2),16)>160?'light':'dark'}}><div className="qa-tracker-toolbar"><label>Sort findings <select aria-label="Sort findings" value={sort} disabled={pending.length>0} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="page">Page</option><option value="section">Section</option></select></label><span>Edits sync with Findings.</span>{pending.length>0&&<><button disabled={saving} onClick={()=>{setSaving(true);void update(pending,shown.revision).then(ok=>{if(ok){setPending([]);setReset(v=>v+1);setError('')}else setError('Could not save these grid edits. They are retained here; refresh findings and retry.')}).finally(()=>setSaving(false))}}>{saving?'Saving…':`Save ${pending.length} edited row${pending.length===1?'':'s'}`}</button><button disabled={saving} onClick={()=>{setPending([]);setError('');setReset(v=>v+1)}}>Discard edits</button></>}</div>
    {error&&<p role="alert" className="qa-organizer-error">{error}</p>}
    <div className="qa-tracker-grid"><Workbook key={`${snapshot.projectKey}-${sort}-${reset}-${theme}`} data={data} showToolbar toolbarItems={activeSheet===AI_SHEET_ID?['undo','redo','font','font-size','bold','italic','text-color','background','horizontal-align','vertical-align','text-wrap','search']:undefined} cellContextMenu={activeSheet===AI_SHEET_ID?['copy','paste']:undefined} headerContextMenu={activeSheet===AI_SHEET_ID?[]:undefined} hooks={{beforeActivateSheet:id=>{if(pending.length&&id!==AI_SHEET_ID){setError('Save or discard your finding edits before switching sheets.');return false}return true},beforeRenderRowHeaderCell:rowHeader,beforeRenderColumnHeaderCell:columnHeader,beforeRenderCell:(cell,_info,ctx)=>{if(!cell?.bg)ctx.fillStyle=colors().bg;return true},afterActivateSheet:id=>{active.current=id;setActiveSheet(id)},beforeUpdateCell:(r,c)=>{return active.current!==AI_SHEET_ID||r>0&&c<snapshot.columns.length+1},beforeDeleteSheet:id=>id!==AI_SHEET_ID,beforeUpdateSheetName:id=>id!==AI_SHEET_ID}} onChange={next=>{
      const managed=next.find(s=>s.id===AI_SHEET_ID)
      if(managed)try{const changes=findingSheetChanges(managed,shown);setPending(previous=>JSON.stringify(previous)===JSON.stringify(changes)?previous:changes);setError('')}catch(cause){setError((cause as Error).message);setReset(v=>v+1)}
      const manual=next.filter(s=>s.id!==AI_SHEET_ID);if(active.current!==AI_SHEET_ID&&JSON.stringify(manual)!==JSON.stringify(manualSheets))onManualChange(manual)
    }}/></div>
  </div>
}
