insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'qa-ephemeral-snapshots',
  'qa-ephemeral-snapshots',
  false,
  26214400,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.qa_snapshots (
  id bigint generated by default as identity primary key,
  site_slug text not null check (char_length(site_slug) between 1 and 100),
  master_id text not null check (char_length(master_id) between 1 and 100),
  item_number integer not null default 0 check (item_number >= 0),
  title text not null default '' check (char_length(title) <= 250),
  notes text not null default '' check (char_length(notes) <= 5000),
  color text not null default '#ff0055' check (color ~ '^#[0-9a-fA-F]{6}$'),
  object_path text not null check (char_length(object_path) between 1 and 1000),
  annotations jsonb not null default '[]'::jsonb check (jsonb_typeof(annotations) = 'array'),
  expires_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (site_slug, master_id, item_number)
);

create table if not exists public.qa_annotation_comments (
  id bigint generated by default as identity primary key,
  site_slug text not null check (char_length(site_slug) between 1 and 100),
  master_id text not null check (char_length(master_id) between 1 and 100),
  item_number integer not null default 0 check (item_number >= 0),
  annotation_id text not null check (char_length(annotation_id) between 1 and 150),
  author_name text not null check (char_length(trim(author_name)) between 1 and 80),
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists qa_snapshots_lookup_idx
  on public.qa_snapshots (site_slug, master_id, item_number);

create index if not exists qa_annotation_comments_lookup_idx
  on public.qa_annotation_comments (site_slug, master_id, item_number, annotation_id, created_at);

alter table public.qa_snapshots enable row level security;
alter table public.qa_annotation_comments enable row level security;

grant select, insert, update on public.qa_snapshots to anon, authenticated;
grant usage, select on sequence public.qa_snapshots_id_seq to anon, authenticated;
grant select, insert on public.qa_annotation_comments to anon, authenticated;
grant usage, select on sequence public.qa_annotation_comments_id_seq to anon, authenticated;

drop policy if exists "QA snapshots are publicly readable" on public.qa_snapshots;
create policy "QA snapshots are publicly readable"
  on public.qa_snapshots for select
  to anon, authenticated
  using (expires_at > now());

drop policy if exists "QA snapshots can be created" on public.qa_snapshots;
create policy "QA snapshots can be created"
  on public.qa_snapshots for insert
  to anon, authenticated
  with check (expires_at > now() and object_path like 'sites/%');

drop policy if exists "QA snapshots can be refreshed" on public.qa_snapshots;
create policy "QA snapshots can be refreshed"
  on public.qa_snapshots for update
  to anon, authenticated
  using (expires_at > now())
  with check (expires_at > now() and object_path like 'sites/%');

drop policy if exists "QA comments are publicly readable" on public.qa_annotation_comments;
create policy "QA comments are publicly readable"
  on public.qa_annotation_comments for select
  to anon, authenticated
  using (true);

drop policy if exists "QA comments can be created" on public.qa_annotation_comments;
create policy "QA comments can be created"
  on public.qa_annotation_comments for insert
  to anon, authenticated
  with check (
    exists (
      select 1
      from public.qa_snapshots snapshot
      where snapshot.site_slug = qa_annotation_comments.site_slug
        and snapshot.master_id = qa_annotation_comments.master_id
        and snapshot.item_number = qa_annotation_comments.item_number
        and snapshot.expires_at > now()
    )
  );

drop policy if exists "QA snapshot objects are readable" on storage.objects;
create policy "QA snapshot objects are readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'qa-ephemeral-snapshots');

drop policy if exists "QA snapshot objects can be created" on storage.objects;
create policy "QA snapshot objects can be created"
  on storage.objects for insert
  to anon, authenticated
  with check (
    bucket_id = 'qa-ephemeral-snapshots'
    and (storage.foldername(name))[1] = 'sites'
  );

drop policy if exists "QA snapshot objects can be refreshed" on storage.objects;
create policy "QA snapshot objects can be refreshed"
  on storage.objects for update
  to anon, authenticated
  using (bucket_id = 'qa-ephemeral-snapshots')
  with check (
    bucket_id = 'qa-ephemeral-snapshots'
    and (storage.foldername(name))[1] = 'sites'
  );
